<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-16T09:31:50 IST" name="Suite1" finished-at="2023-04-16T09:34:35 IST" duration-ms="164122">
    <groups>
      <group name="kite">
        <method signature="AppiumTest.asetUp()[pri:0, instance:core.AppiumTest@6fe7aac8]" name="asetUp" class="core.AppiumTest"/>
        <method signature="AppiumTest.btestApp()[pri:0, instance:core.AppiumTest@6fe7aac8]" name="btestApp" class="core.AppiumTest"/>
        <method signature="AppiumTest.cbuylist()[pri:0, instance:core.AppiumTest@6fe7aac8]" name="cbuylist" class="core.AppiumTest"/>
      </group> <!-- kite -->
    </groups>
    <test started-at="2023-04-16T09:31:50 IST" name="Test Suite 2" finished-at="2023-04-16T09:34:35 IST" duration-ms="164122">
      <class name="core.AppiumTest">
        <test-method signature="asetUp()[pri:0, instance:core.AppiumTest@6fe7aac8]" started-at="2023-04-16T09:31:51 IST" name="asetUp" finished-at="2023-04-16T09:32:31 IST" duration-ms="39940" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asetUp -->
        <test-method signature="btestApp()[pri:0, instance:core.AppiumTest@6fe7aac8]" started-at="2023-04-16T09:32:31 IST" name="btestApp" finished-at="2023-04-16T09:33:35 IST" duration-ms="64347" status="FAIL">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[Index 2 out of bounds for length 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
at core.AppiumTest.getholdings(AppiumTest.java:252)
at core.AppiumTest.btestApp(AppiumTest.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- btestApp -->
        <test-method signature="cbuylist()[pri:0, instance:core.AppiumTest@6fe7aac8]" started-at="2023-04-16T09:33:35 IST" name="cbuylist" finished-at="2023-04-16T09:34:34 IST" duration-ms="59242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cbuylist -->
      </class> <!-- core.AppiumTest -->
    </test> <!-- Test Suite 2 -->
  </suite> <!-- Suite1 -->
</testng-results>
